version: '3.8'

services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env
      - .env.example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
      - .env.example
    depends_on:
      - db
    volumes:
      - .:/app
    networks:
      - app_network

  tests:
    build: .
    env_file:
      - .env
      - .env.example
    depends_on:
      - db
    volumes:
      - .:/app
    command: poetry run pytest
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
